export MLFLOW_EXPERIMENT_ID="6"
export MLFLOW_TRACKING_URI="THIS_IS_SECRET";
export AWS_ACCESS_KEY_ID="THIS_IS_SECRET";
export AWS_SECRET_ACCESS_KEY="THIS_IS_SECRET";
export BACKEND_STORE_URI="THIS_IS_SECRET";
export ARTIFACT_ROOT="THIS_IS_SECRET";